cart/urls.py
from django.urls import path
from cart.views import add_to_cart,checkout,cart,hx_menu_cart,update_cart,hx_cart_total,success_view


urlpatterns = [
    path('add_to_cart/<int:product_id>/',add_to_cart,name='add_to_cart'),
    path('',cart,name='cart'),
    path('checkout/',checkout,name='checkout'),
    path('hx_menu_cart/',hx_menu_cart,name='hx_menu_cart'),
    path('hx_cart_total/',hx_cart_total,name='hx_cart_total'),
    path('update_cart/<int:product_id>/<str:action>/',update_cart, name='update_cart'),
]

order/urls.py
from django.urls import path
from .views import start_order,cancel_view
from cart.views import success_view
urlpatterns = [
     path('start_order/',start_order,name='start_order'),
     path('purchased/loading',success_view, name='payment-successful'),
]

seller/urls.py
from django.urls import path
from . import views
from .views import ProductDeleteView,ProductUpdateView

urlpatterns = [
    path("", views.index,name='sellers'),
    path("create-shop/", views.create_shop, name="create-shop"),
    path("shop/<uuid:shop_id>/add-item/", views.add_item),
    path("shop/<uuid:shop_id>/items/<uuid:product_id>/", views.view_item),
    path("shop/<uuid:shop_id>/", views.view_shop,name="dashboard"),
    path("shop/<uuid:shop_id>/orders/", views.view_orders),
    path("shop/<uuid:shop_id>/orders/<str:order_item>/", views.view_order),
    path('shop/<uuid:shop_id>/<slug:slug>/delete', ProductDeleteView.as_view(), name='product-delete'),
    path('shop/<uuid:shop_id>/<slug:slug>/update', ProductUpdateView.as_view(), name='product-update'),
]

shoptinga/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from core.sitemaps import PostSitemap
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from two_factor.urls import urlpatterns as tf_urls

sitemaps = {
		"posts": PostSitemap,
}
urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('', include(tf_urls)),
    path('account/',include('accounts.urls')),
    path('cart/',include('cart.urls')),
    path('order/',include('order.urls')),
    path('seller/',include('seller.urls')),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='core/password_reset.html'),name='password_reset'),
     path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_done.html'),name='password_reset_done'),
     path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_complete.html'),name='password_reset_complete'),
      path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_confirm.html'),name='password_reset_confirm'),
    path('sitemap.xml', sitemap,{'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
]
handler404 = "core.views.page_not_found_view"

if settings.DEBUG:
	
    urlpatterns +=static (settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

order/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import Profile
from product.models import Product
from django.conf import settings
class Order(models.Model):
	user = models.ForeignKey(User,related_name='orders',blank=True,null=True,on_delete = models.CASCADE)	
	created_at = models.DateTimeField(auto_now_add=True)
	paid = models.BooleanField(default=False)
	paid_amount = models.IntegerField(blank=True,null=True)
	
	class Meta:
		ordering = ['-created_at',]
	def get_total_price(self):
		if self.paid_amount:
			return self.paid_amount
		return 0
		
class Orderitem(models.Model):
	item_id = models.UUIDField()
	paid = models.BooleanField(default=False)
	order = models.ForeignKey(Order,related_name='items',on_delete=models.CASCADE)
	product= models.ForeignKey(Product,related_name='items',on_delete=models.CASCADE)
	price = models.IntegerField()
	quantity = models.IntegerField(default=1)
	
	def get_total_price(self):
		return self.price
		
# Create your models here.

seller/models.py
from django.db import models
import uuid
from django.core.files import File
from shoptinga.util import unique_slug_generator
from six import python_2_unicode_compatible
from django.dispatch import receiver
from django.db.models.signals import pre_save
from PIL import Image
from io import BytesIO
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User

class Shop(models.Model):
    user = models.ForeignKey(User,related_name="shops",on_delete=models.CASCADE)
    shop_id = models.UUIDField(default=uuid.uuid4, unique=True)
    balance = models.FloatField(default=0)
    commision = models.IntegerField(default=3)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    category = models.CharField(max_length=225)
    logo = models.ImageField(upload_to="logo,")
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    bank_name = models.CharField(max_length=255,blank=True,null=True)
    bank_acct = models.CharField(max_length=15,blank=True,null=True)
    w_address = models.CharField(max_length=225,blank=True,null=True)
    approved = models.BooleanField(default=False)
    
    def __str__(self):
    	return self.name
    

	

seller/forms.py
from django import forms
from product.models import Product

class ProductForm(forms.ModelForm):
	class Meta:
		model = Product
		fields = ['name','description','price','category','shop_id']

order/views.py
from django.shortcuts import render,redirect,reverse
from .models import Order,Orderitem
from cart.cart import Cart
from coinbase_commerce.client import Client
from shoptinga import settings
from django.http import JsonResponse, HttpResponse
import requests
import paystack
from django.contrib import messages

def start_order(request):
	return render(request, 'cart/checkout.html', context)





def cancel_view(request):
    return render(request, 'cart/cancel.html', {'public_key': settings.PAYSTACK_PUBLIC_KEY})
    
	

seller/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http.response import JsonResponse
from json.decoder import JSONDecodeError
import os
from django.urls import reverse
from seller.models import Shop
from django.http import HttpResponseRedirect, HttpResponse
import requests
from order.models import Orderitem, Order
from accounts.models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from product.models import Product
from django.contrib import messages
from django.views.generic import UpdateView, DeleteView, CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

@login_required
def index(request):
    shops = Shop.objects.filter(user=request.user)
    return render(request, "seller/index.html", {
        "shops": shops
    })

@login_required
def create_shop(request):
    if request.method == "POST":
        name = request.POST["name"]
        description = request.POST["description"]
        logo = request.FILES.get('logo')
        category = request.POST['category']
        phone = request.POST['phone']
        email = request.POST['email']
        country  = request.POST['country']
        bank_name  = request.POST['bank_name']
        bank_acct = request.POST['bank_acct']
        w_address  = request.POST['w_address']
        
        if Shop.objects.filter(name=name).exists():
            messages.error(request, 'A creator account with the unique name already exist.')
            return redirect('create-shop')
     	    
        Shop(name=name, description=description, logo=logo,phone=phone,email=email,bank_name=bank_name,bank_acct=bank_acct,country=country,w_address=w_address,category=category,user=request.user).save()
        return redirect("sellers")
    else:
     	  	return render(request, "seller/create-shop.html")
     	  	         
def add_item(request,shop_id):
	if request.method == 'POST':
		name=request.POST["name"]
		description = request.POST["description"]
		price = float(request.POST["price"])
		image = request.FILES.get('image')
		thumbnail = request.FILES.get('thumbnail')
		content = request.FILES.get('content')
		Product(name=name, description=description, price=price,image=image,thumbnail=thumbnail,content=content,shop_id=shop_id).save()
		product = Product.objects.filter(name=request.POST["name"], description=request.POST["description"], price=float(request.POST["price"]), shop_id=shop_id)[::-1][0]
		
		return HttpResponseRedirect(f"/seller/shop/{shop_id}/")
	else:
		return render(request, "seller/add-item.html")
		
def view_item(request, shop_id, product_id):
    shop = Shop.objects.get(shop_id=shop_id)
    product = Product.objects.get(product_id=product_id)

    return render(request, "seller/view-item.html", {
        "shop": shop,
        "product": product,
    })

"""
    Function View
"""

def view_shop(request, shop_id):
    shop = get_object_or_404(Shop,shop_id=shop_id)
    products = Product.objects.filter(shop_id=shop_id)
    data = []

    for product in products:
        order = Orderitem.objects.filter(item_id=product.product_id)
        if len(order) != 0:
            data.append([o for o in order])

    items_data = []

    return render(request, "seller/shop.html", {
        "data": data,
        "data_length": len(data),
        "items": items_data,
        "shop":shop,
        "products":products,
    })

def view_orders(request, shop_id):
    products = Product.objects.filter(shop_id=shop_id)
    data = []

    for product in products:
        order = Orderitem.objects.filter(item_id=product.product_id)
        if len(order) != 0:
            data.append([o for o in order])

    print(data)

    return render(request, "seller/orders.html", {
        "data": data,
        "data_length": len(data)
    })
    
def view_order(request, shop_id, order_item):
    order_item_2 = OrderItem.objects.get(id=order_item)
    order = Order.objects.get(payment_id=order_item_2.payment_id)
    user = User.objects.get(id=order.user_id)
    profile = Profile.objects.get(user_id=order.user_id)
    item = Item.objects.get(item_id=order_item_2.item_id)


    return render(request, "seller/order.html", {
        "order_item": order_item_2,
        "order": order,
        "profile": profile,
        "item": item,
        "user": user
    })

class ProductDeleteView(DeleteView):
	model = Product
	success_url = '/seller'
	template_name = 'seller/confirm_delete.html'
	

class ProductUpdateView(UpdateView):
	model = Product
	fields = ['name', 'image','thumbnail','price','description','content']
	template_name = 'seller/product_update.html'
	success_url = '/seller'

seller/templates/seller/add-item.html
     {% extends 'seller/base.html' %}
      {% block title %}Upload product{% endblock %}
{% load tailwind_filters %}
      {% block content %}

      <div class="max-w-lg flex flex-wrap  mx-auto p-6 ">
    <div class="w-full bg-gray-100 p-6 rounded-xl">
      <h1 class="mb-6 text-2xl font-bold">Add Product</h1>
   <form action="." method="post" class="space-y-3" enctype="multipart/form-data">
     {% csrf_token %}
     <div>
  <label class="font-bold text-sm">Name</label>
       <input type="text" name="name" id="" class="w-full mt-2 py-4 px-6 bg-white rounded-xl " required />
   <label class="font-bold text-sm">Description</label>
       <textarea  name="description" id="" class="w-full mt-2 py-4 px-6 bg-white rounded-xl " ></textarea>
  <label class="font-bold block mb-2 text-sm font-medium text-gray-900 dark:text-white" for="file_input">Thumbnail/Cover image</label>
<input class="font-bold block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-yellow-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" aria-describedby="file_input_help" id="file_input" accept="image/*" name="thumbnail"type="file">
<p class="mt-1 text-sm text-gray-500 dark:text-gray-300" id="file_input_help">SVG, PNG, JPG (MAX. 400 x 400px).</p>
<label class="font-bold block mb-2 text-sm font-medium text-gray-900 dark:text-white" for="file_input">Image</label>
<input class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-yellow-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" aria-describedby="file_input_help" id="file_input" accept="image/*" name="image"type="file">
<p class="mt-1 text-sm text-gray-500 dark:text-gray-300" id="file_input_help">SVG, PNG, JPG (MAX. 400 x 400px).</p>

    <hr />
    <label for="input-group-1" class="block mb-2 text-sm font-bold text-gray-900 dark:text-white">Price</label>
<div class="relative mb-6">
  <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v12m-3-2.818l.879.659c1.171.879 3.07.879 4.242 0 1.172-.879 1.172-2.303 0-3.182C13.536 12.219 12.768 12 12 12c-.725 0-1.45-.22-2.003-.659-1.106-.879-1.106-2.303 0-3.182s2.9-.879 4.006 0l.415.33M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
</svg>
  </div>
  <input type="text" id="input-group-1" name="price" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="23">
</div>
       <label class="font-bold mt-5 text-sm">Content</label>
<div class="flex items-center justify-center w-full">
    <label for="dropzone-file" class="flex flex-col items-center justify-center w-full h-64 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 dark:hover:bg-bray-800 dark:bg-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:hover:bg-gray-600">
        <div class="flex flex-col items-center justify-center pt-5 pb-6">
            <svg aria-hidden="true" class="w-10 h-10 mb-3 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"></path></svg>
            <p class="mb-2 text-sm text-gray-500 dark:text-gray-400"><span class="font-semibold">Click to upload</span> or drag and drop</p>
            <p class="text-xs text-gray-500 dark:text-gray-400">PDF or ZIP Max(100mb)</p>
          
        </div>
        <input id="dropzone-file" type="file" name="content" class="hidden" onchange="showFileName()"/>
          <p id="selected-file-name" class="absolute inset-y-0 rigth-0 flex items-center pr-4 text-gray-700"></p>
    </label>
</div> 
   
      {% if form.errors %}
     {% for field in form %}
     {% for error in field.errors%}
     <div class="p-6 bg-red-200 text-red-800 rounded-xl ">
       <p>{{ error|escape }}</p>
     </div>
     {% endfor %}
     {% endfor %}
     {% for error in form.non_fields_errors %}
 <div class="p-6 bg-red-200 text-red-800 rounded-xl ">
       <p>{{ error|escape }}</p>
     </div>
     {% endfor %}
     {% endif %}
     <div>
    <button class="mt-6 inline-block px-8 py-4 rounded-xl bg-yellow-500 text-white hover:bg-yellow-700">Upload</button>
  </div>
   </form>
    </div>
      </div>
      {% endblock %}
      <script>
      function showFileName(input) {
        var input = document.getElementById('dropzone-file');
        var fileName = input.value.split('\\').pop();
          document.getElementById('selected-file-name').textContent = fileName;
        }
      </script>

seller/templates/seller/confirm_delete.html
      {% extends 'seller/base.html' %}
      {% block title %}{{ shop.name }}{% endblock %}
      {% block content %}

   
      
      <div class="max-w-6xl mx-auto flex flex-wrap py-6 px-6 xl:px-0">
        <div class="w-full pr-6mb-6 p-6 bg-red-400 br-yellow-500 text-white rounded-xl">
          <form class="" action="" method="post">
                {% csrf_token %}
    <fieldset class="form-group">
      <legend class="text-xl font-bold mb-4"> Delete Post</legend>
      <h1>Are you sure you want to delete this product <span class="font-bold">"{{ object.name }}"</span></h1>
    </fieldset>
    <div class="form-group">
      <button class="bg-red-700 rounded-xl mb-3 p-3" type="submit">Yes, Delete</button>
   <a class="ml-3 bg-yellow-400 p-3 rounded-xl" href="{% url 'sellers' %}">Cancel</a>
    </div>
          </form>
        </div>
        </div>
        {% endblock %}

seller/templates/seller/create-shop.html
      {% extends 'seller/base.html' %}
      {% block title %}Create Creator Account{% endblock %}
      {% block content %}

   
      <div class="max-w-6xl flex flex-wrap items-start mx-auto py-2 px-6 xl:px-0">
<form class="" action="." method="post" enctype="multipart/form-data" >
            {% csrf_token %}
        <div class="product w-full lg:w-3/4">
          <h1 class="mb-5 text-3xl">Signup For A Creator Account</h1>
          
          <div class="w-full pr-6">
            <div class="mb-6 p-6 bg-gray-100 rounded-xl">
  <div class="mb-4">

<label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white" for="file_input">Brand logo/image</label>
<input class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-yellow-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" aria-describedby="file_input_help" id="file_input" accept="image/*" name="logo"type="file">
<p class="mt-1 text-sm text-gray-500 dark:text-gray-300" id="file_input_help">SVG, PNG, JPG (MAX. 800x400px).</p>

              </div>
  <div class="mb-4">
                <label class="inline-block mb-2">Unique / Brand Name </label>
                <input type="text" name="name" class="w-full p-5 rounded-xl" value="" />
              </div>
  <div class="mb-4">
                <label class="inline-block mb-2">Description</label>
                <p class="text-sm mt-1 mb-1 text-gray-400">*Describe yourself/Brand,who you are, what you do/sell with just 50 characters* </p>
                <input type="text" name="description" class="w-full p-10 rounded-xl" value="" />
              </div>
<label for="id_category" class="block   mb-2">Category that suites your Brand most<span class="asteriskField">*</span> </label> <div class="mb-3"> <div class="relative"><select class="bg-white focus:outline-none border border-gray-300 rounded-lg py-2 px-4 block w-full appearance-none leading-normal text-gray-700" name="category"> <option value="">---------</option>
> <option value="E-books">E-books</option> 
<option value="Online courses">Online Courses</option> 
<option value="Digital Arts/Nfts">Digital Arts/Nft's</option> 
<option value="Softwares">Softwares</option> 
<option value="Other">Other</option>

</select><div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700"> <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"></path> </svg> </div></div>
       
            </div>
  <div class="mb-6 p-6 bg-gray-100 rounded-xl">
              <h2 class="mb-5 uppercase text-lg">Contact information</h2>
              <div class="mb-4">
                <label class="inline-block mb-2">Email</label>
                <input type="email" name="email" class="w-full p-5 rounded-xl" value="{{ request.user.email }}" />
              </div>
                <div class="mb-4">
                <label class="inline-block mb-2">Country</label>
                <input type="text" name="country" class="w-full p-5 rounded-xl" placeholder="Nigeria" />
              </div>
   <div class="mb-4">
                <label class="inline-block mb-2">Phone</label>
                                <p class="text-sm mt-1 mb-1 text-gray-400">your mobile number should include your country code e.g 2349060620279</p>
                <input type="phone" name="phone" class="w-full p-5 rounded-xl" value="" />
              </div>
            </div>
          </div>
        </div>
    <div>
  <div class="mb-6 p-6 bg-gray-100 rounded-xl">
              <h2 class="mb-5 uppercase text-lg">Payment information</h2>
                              <p class="text-sm mt-1 mb-1 text-gray-400">*You are expected to only fill one  payment info, if you want to recieve your earnings in crypto fill the wallet address field ,but if you want to recieve your earnings in fiat money fill the bank details field*</p>
               <div class="mb-4">
                <label class="inline-block mb-2">Crypto wallet address</label>
                <input type="text" name="w_address" class="w-full p-5 rounded-xl" value="" />
              </div>
  <p class="text-sm mt-1 mb-1 text-gray-400">*we advice you put your business/shop correct bank details.* </p>
  <div class="mb-4">
                <label class="inline-block mb-2">Bank name</label>
                <input type="text" name="bank_name" class="w-full p-5 rounded-xl" value="" />
              </div>
 <div class="mb-4">
                <label class="inline-block mb-2">Account no</label>
                <input type="number" name="bank_acct" class="w-full p-5 rounded-xl" value="" />
              </div>
            </div>
            
          <button class="inline-block px-8 py-4 rounded-xl bg-yellow-500 hover:bg-yellow-700">Submit</button>
          
        </div>
        </form>
        </div>
        {% endblock %}

seller/templates/seller/index.html
      {% extends 'seller/base.html' %}
      {% block title %}Creator{% endblock %}
      {% block content %}

   
      
      <div class="max-w-6xl mx-auto flex flex-wrap py-6 px-6 xl:px-0">

   <h2 class="mb-5 uppercase text-lg font-bold">Creator Account</h2>
      {% if not shops %}
  <div class="mb-6 p-6 bg-gray-100 rounded-xl">
<h2 class="mb-5 uppercase text-lg">Create a creator account</h2>
<p>You are not a creator </p>
     <a class="mt-6 inline-block px-8 py-4 rounded-xl bg-yellow-500 text-white hover:bg-yellow-700" href="/seller/create-shop/" class="card-link">Create</a>
    </div>
      {% endif %}
          {% for s in shops.all %}

   <div class="w-full  p-6">
            <img class="w-full rounded-xl hover:shadow-lg" src="{{ s.logo.url }}" alt="" />
          <div class="pt-3 flex items-center justify-between">
            <p class="text-medium">{{ s.name }}{% if s.approved == True %}<span class="text-yellow-500"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
  <path fill-rule="evenodd" d="M8.603 3.799A4.49 4.49 0 0112 2.25c1.357 0 2.573.6 3.397 1.549a4.49 4.49 0 013.498 1.307 4.491 4.491 0 011.307 3.497A4.49 4.49 0 0121.75 12a4.49 4.49 0 01-1.549 3.397 4.491 4.491 0 01-1.307 3.497 4.491 4.491 0 01-3.497 1.307A4.49 4.49 0 0112 21.75a4.49 4.49 0 01-3.397-1.549 4.49 4.49 0 01-3.498-1.306 4.491 4.491 0 01-1.307-3.498A4.49 4.49 0 012.25 12c0-1.357.6-2.573 1.549-3.397a4.49 4.49 0 011.307-3.497 4.49 4.49 0 013.497-1.307zm7.007 6.387a.75.75 0 10-1.22-.872l-3.236 4.53L9.53 12.22a.75.75 0 00-1.06 1.06l2.25 2.25a.75.75 0 001.14-.094l3.75-5.25z" clip-rule="evenodd" />
</svg>
</span>{% endif %}</p>

          </div>
          <p class="pt-1 text-gray-400">{{ s.description }} </p>
        </div>
     {% if s.approved == False %}
<p class="mt-6 text-green-500 inline-block">Approval pending......</p>
{% else %}
                    <a class="mt-6 inline-block px-8 py-4 rounded-xl bg-yellow-500 text-white hover:bg-yellow-700" href="/seller/shop/{{ s.shop_id }}/" class="card-link">Go to dashbord <span><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M17.25 8.25L21 12m0 0l-3.75 3.75M21 12H3" />
</svg>
</span></a>
                    {% endif %}
      {% endfor %}
        </div>
        {% endblock %}

seller/templates/seller/orders.html
      {% extends 'seller/base.html' %}
      {% block title %}Purchased products{% endblock %}
      {% block content %}

   
      
      <div class="max-w-6xl mx-auto flex flex-wrap py-6 px-6 xl:px-0">
        <h1 class="text-2xl font-bold w-full my-2"> Products Purchased</h1>
        <br>
         {% for d in data %}
      
          
<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
                    Product name
                </th>
                <th scope="col" class="px-6 py-3">
                    Quantity
                </th>
                <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
                    Category
                </th>
                <th scope="col" class="px-6 py-3">
                    Price
                </th>
            </tr>
        </thead>
        {% for i in d %}
        <tbody>
            <tr>
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800">
                    {{ i.product.name }}
                </th>
                <td class="px-6 py-4">
                    {{ i.quantity }}
                </td>
                <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                    {{ i.product.category }}
                </td>
                <td class="px-6 py-4">
                    ${{ i.product.price }}
                </td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
</div>
        
    {% endfor %}
        </div>
 
        {% endblock %}

seller/templates/seller/product_update.html
      {% extends 'seller/base.html' %}
{% load tailwind_filters %}
      {% block title %}Update product{% endblock %}
      {% block content %}

   
      <div class="max-w-6xl flex flex-wrap items-start mx-auto py-2 px-6 xl:px-0">
        <h1 class="mt-2 mb-3 text-2xl font-bold">Update product</h1>
        <div class="w-full pr-6mb-6 p-6 bg-gray-100 rounded-xl">
          <form method="post" accept-charset="utf-8">
            {% csrf_token %}
{{ form|crispy }}
  <button class="inline-block px-8 py-4 rounded-xl bg-yellow-500 hover:bg-yellow-700">Submit</button>
          </form>
        </div>
        </div>
        
        {% endblock %}

seller/templates/seller/view-item.html
      {% extends 'seller/base.html' %}
      {% block title %}My products{% endblock %}
      {% block content %}

   
      
      <div class="max-w-6xl mx-auto flex flex-wrap py-6 px-6 xl:px-0">
        shop
        </div>
        {% endblock %}